### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Bdelmedico** [hackmods/autoXOA#11]
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

cat /root/.npm/_logs/2018-05-22T20_30_56_704Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.0.1
3 info using node@v10.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xo-server@5.13.0~prestart: xo-server@5.13.0
6 info lifecycle xo-server@5.13.0~start: xo-server@5.13.0
7 verbose lifecycle xo-server@5.13.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle xo-server@5.13.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/xoa/xo-server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle xo-server@5.13.0~start: CWD: /xoa/xo-server
10 silly lifecycle xo-server@5.13.0~start: Args: [ '-c', 'node bin/xo-server' ]
11 silly lifecycle xo-server@5.13.0~start: Returned: code: 1  signal: null
12 info lifecycle xo-server@5.13.0~start: Failed to exec start script
13 verbose stack Error: xo-server@5.13.0 start: `node bin/xo-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid xo-server@5.13.0
15 verbose cwd /xoa/xo-server
16 verbose Linux 4.4.0-121-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.0.0
19 verbose npm  v6.0.1
20 error code ELIFECYCLE
21 error errno 1
22 error xo-server@5.13.0 start: `node bin/xo-server`
22 error Exit status 1
23 error Failed at the xo-server@5.13.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

--------------

curl -L autoXOA.zxcv.us | sudo -i bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
######################################################
##                    Auto XOA                      ##
100  52##                                                  ##
72  100  5272    0     0   2444      ## Deploy Xen Orchestra from source, automatically. ##
0  0:00:02  0:00:02 --:--:--  2444
######################################################
You are root.
User selected to install XOA
Make a selection
User selected to install XOA-Server && XOA-Web.
Performing initial updates
Installing updates
Hit:1 https://dl.yarnpkg.com/debian stable InRelease
Hit:2 http://br.archive.ubuntu.com/ubuntu xenial InRelease                                          
Hit:3 http://br.archive.ubuntu.com/ubuntu xenial-updates InRelease                                  
Hit:4 http://br.archive.ubuntu.com/ubuntu xenial-backports InRelease                                
Hit:5 https://deb.nodesource.com/node_8.x xenial InRelease                                          
Hit:6 http://repo.zabbix.com/zabbix/3.4/ubuntu xenial InRelease          
Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease        
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing dependencies
Command: curl + n stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16696  100 16696    0     0  51640      0 --:--:-- --:--:-- --:--:-- 51690
Command: apt-get --yes --force-yes install build-essential redis-server libpng-dev git python-minimal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
build-essential is already the newest version (12.1ubuntu2).
libpng12-dev is already the newest version (1.2.54-1ubuntu1).
redis-server is already the newest version (2:3.0.6-1).
git is already the newest version (1:2.7.4-0ubuntu1.3).
python-minimal is already the newest version (2.7.12-1~16.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Command: npm install -g bower
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
+ bower@1.8.4
updated 1 package in 1.833s
Starting Install_XOA-server install
Command: git clone -b stable http://github.com/vatesfr/xo-server
fatal: destination path 'xo-server' already exists and is not an empty directory.
Command: npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle xo-server@5.13.0~prepublish: cannot run in wd xo-server@5.13.0 npm run build (wd=/xoa/xo-server)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 84 packages from 63 contributors in 8.979s
[!] 398 vulnerabilities found [12344 packages audited]
    Severity: 357 Low | 32 Moderate | 9 High
    Run `npm audit` for more detail

Command: npm run build

> xo-server@5.13.0 prebuild /xoa/xo-server
> index-modules src/api src/xapi/mixins src/xo-mixins

index generated src/api/index.js
index generated src/xapi/mixins/index.js
index generated src/xo-mixins/index.js

> xo-server@5.13.0 build /xoa/xo-server
> gulp build --production

[17:30:31] Using gulpfile /xoa/xo-server/gulpfile.js
[17:30:31] Starting 'build'...
[17:30:31] Starting 'clean'...
[17:30:31] Finished 'clean' after 30 ms
[17:30:31] Starting 'buildCoffee'...
[17:30:31] Starting 'buildEs6'...
[17:30:34] Finished 'buildCoffee' after 2.37 s
[17:30:41] Finished 'buildEs6' after 10 s
[17:30:41] Finished 'build' after 10 s
Command: curl -L https://raw.githubusercontent.com/hackmods/autoXOA/master/config/xo-server.yaml > .xo-server.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3704  100  3704    0     0  12595      0 --:--:-- --:--:-- --:--:-- 12598
Starting Install_XOA-web install
Command: git clone -b stable http://github.com/vatesfr/xo-web
fatal: destination path 'xo-web' already exists and is not an empty directory.
Command: npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle xo-web@5.13.0~prepublish: cannot run in wd xo-web@5.13.0 npm run build (wd=/xoa/xo-web)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 84 packages from 63 contributors in 9.892s
[!] 446 vulnerabilities found [16579 packages audited]
    Severity: 398 Low | 38 Moderate | 10 High
    Run `npm audit` for more detail

Command: npm run build	

> xo-web@5.13.0 build /xoa/xo-web
> npm run build-indexes && NODE_ENV=production gulp build

> xo-web@5.13.0 build-indexes /xoa/xo-web
> index-modules --auto src

index generated src/common/intl/locales/index.js
index generated src/common/themes/index.js
[17:30:53] Using gulpfile /xoa/xo-web/gulpfile.js
[17:30:53] Starting 'build'...
[17:30:53] Starting 'buildPages'...
[17:30:53] Starting 'buildScripts'...
[17:30:53] Starting 'buildStyles'...
[17:30:53] Starting 'copyAssets'...
[17:30:54] 'buildStyles' errored after 461 ms
[17:30:54] Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
    at module.exports (/xoa/xo-web/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/xoa/xo-web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/xoa/xo-web/node_modules/gulp-sass/index.js:187:21)
[17:30:54] 'build' errored after 465 ms
[17:30:54] The following tasks did not complete: buildPages, buildScripts, copyAssets
[17:30:54] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xo-web@5.13.0 build: `npm run build-indexes && NODE_ENV=production gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xo-web@5.13.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-22T20_30_54_120Z-debug.log
Starting autoXOA install
Command: curl -L autoxoa.zxcv.us > autoXOA.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5272  100  5272    0     0  10299      0 --:--:-- --:--:-- --:--:-- 10299
All installations have been completed.
IP Configuration
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 1a:d7:ba:65:27:dc brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.189/24 brd 10.10.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::18d7:baff:fe65:27dc/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 56:1c:b8:94:8e:83 brd ff:ff:ff:ff:ff:ff
 
Starting xo-server

> xo-server@5.13.0 start /xoa/xo-server
> node bin/xo-server

internal/buffer.js:53
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:53:11)
    at Buffer.readUInt32BE (internal/buffer.js:198:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xo-server@5.13.0 start: `node bin/xo-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xo-server@5.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-22T20_30_56_704Z-debug.log
Thank you for using AutoXOA. Leave feedback at zxcv.us or contribute to the Github project.

**Comment by phckopper** [comment]
Got the same error, Debian 8.0

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose stack Error: ENOENT: no such file or directory, open '/package.json'
5 verbose cwd /
6 verbose Linux 4.9.0-6-amd64
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v10.2.1
9 verbose npm  v5.6.0
10 error path /package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]`

I believe somewhere it's looking for the package.json in the root directory instead of the actual installation one?

**Comment by Bdelmedico** [comment]
dude ... it's not even going to work ...

they change the reositorio "http://github.com/vatesfr/xo-server"

we'll have to wait for the uptime of the script
