### ISSUE TITLE
On newly installed Debian Jessie ( 8.7.1 ) x64 Install script completes, but xoa fails to start 

### ISSUE THREAD

**Issue by cgoudie** [hackmods/autoXOA#5]
Nearly completely clean install (Debian and salt-minion)

Starting xo-server

> xo-server@5.6.4 start /xoa/xo-server
> node bin/xo-server

  app-conf /xoa/xo-server/config.json +0ms
  app-conf /xoa/xo-server/.xo-server.yaml +2ms
  xo:main Configuration loaded. +15ms
  xo:main Web server listening on http://[::]:80 +6ms
  xo:perf blocked for 84ms +146ms
[WARN] start error: Error: spawn vgchange ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  xo:main Setting up / → /xoa/xo-web/dist +279ms
  xo:perf blocked for 182ms +4ms

Hitting the http://<ip> does show the xoa sign-in screen. When I try to sign in with an invalid un/pw it tells me bad login. When I try to sign in with the default un/pw, it signs me in and gives me a spinning icon indefinitely.

**Comment by cgoudie** [comment]
I believe this is directly related to the npm run build on the xo-web

[18:08:43] 'buildScripts' errored after 52 s
[18:08:43] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected character '`'
[18:08:43] 'build' errored after 52 s

**Comment by hackmods** [comment]
Thanks for the feedback! Ill take a look and I should have a fix out my tomorrow end of day!

**Comment by jrubenc** [comment]
4 months later, same problem persists on a fresh new install.

`
> xo-server@5.10.1 start /xoa/xo-server
> node bin/xo-server

  app-conf /xoa/xo-server/config.json +0ms
  app-conf /xoa/xo-server/.xo-server.yaml +2ms
  xo:main Configuration loaded. +14ms
  xo:main Web server listening on http://[::]:80 +8ms
  xo:perf blocked for 60ms +117ms
[WARN] start error: Error: spawn vgchange ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  xo:main Setting up / → /xoa/xo-web/dist +497ms
  xo:perf blocked for 405ms +8ms
`

**Comment by jrubenc** [comment]
4 months later, same problem persists on a new fresh-n-clean install:

> \> xo-server@5.10.1 start /xoa/xo-server
> \> node bin/xo-server

>  app-conf /xoa/xo-server/config.json +0ms
  app-conf /xoa/xo-server/.xo-server.yaml +2ms
  xo:main Configuration loaded. +14ms
  xo:main Web server listening on http://[::]:80 +8ms
  xo:perf blocked for 60ms +117ms
[WARN] start error: Error: spawn vgchange ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  xo:main Setting up / → /xoa/xo-web/dist +497ms
  xo:perf blocked for 405ms +8ms
